### ISSUE TITLE
描述在这里

### ISSUE THREAD

**Issue by duTianze** [Lingo1101/-#1]
<img width="672" alt="1" src="https://user-images.githubusercontent.com/33278478/65655729-c1cd3480-e04f-11e9-8018-396722af3f6f.png">

**Comment by Lingo1101** [comment]
哈哈哈嗝尴尬------------------ 原始邮件 ------------------
发件人: "杜天泽"<notifications@github.com>
发送时间: 2019年9月26日(星期四) 中午11:21
收件人: "Lingo1101/-"<-@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Lingo1101/-] 描述在这里 (#1)




 
&mdash;

**Comment by Lingo1101** [comment]
我是那个新建test2一路下去有个创建新文件点击没反应，这个箭头指的这个说明还是直接粘贴上去的------------------ 原始邮件 ------------------
发件人: "杜天泽"<notifications@github.com>
发送时间: 2019年9月26日(星期四) 中午11:21
收件人: "Lingo1101/-"<-@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Lingo1101/-] 描述在这里 (#1)




 
&mdash;
